import React from 'react'
import Head from 'next/head'
import { useState } from 'react'
export default function index() {
  const [link,setLink] = useState('')
  const [linkSementara,setLinkSementara] = useState('')
  function download(){
    setLink(linkSementara)
  }
  return (
    <>
      <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>
          <title>Youtube Downloader</title>
      </Head>
      <div>
          <h1 className='text-center fw-bold mt-5'>Youtube Downloader</h1>
          <div class="w-min  p-5 input-group">
              <input type="text" onChange={(e)=>{setLinkSementara(e.target.value)}} class="form-control w-min" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" placeholder='Masukkan Link Youtube'/>
              <span onClick={download} className='input-group-text'><img src='/images/search.png'/></span>
          </div>
        
      </div>
      {link ? (
        <iframe 
          id="widgetv2Api" 
          src={`https://convert2mp3s.com/api/widgetv2?url=${link}`} 
          width="100%"
          height="800px" 
          scrolling="no" 
          >
        </iframe>
      ):null
    }
      
    </>
  )
}
